---
detectors:
  TooManyInstanceVariables:
    max_instance_variables: 6
  TooManyStatements:
      max_statements: 6
  IrresponsibleModule:
    enabled: false
  ControlParameter:
    enabled: false
  DuplicateMethodCall:
    allow_calls:
      - match
  FeatureEnvy:
    exclude:
      - 'Wax::Configurable'
      - 'Wax::Project'