---
detectors:
  TooManyStatements:
      max_statements: 13
  IrresponsibleModule: # Should be able to remove later!!!
    enabled: false
  FeatureEnvy:
    enabled: false
  ControlParameter:
    enabled: false
  TooManyInstanceVariables:
    max_instance_variables: 5
  DuplicateMethodCall:
    max_calls: 3
    allow_calls: [config]
  Attribute: # Should fix
    enabled: false
  InstanceVariableAssumption: # Should fix
    enabled: false
  NestedIterators:
    ignore_iterators: [find, tap]