---
detectors:
  Attribute:
    exclude: [iiif_manifest]
  TooManyStatements:
    max_statements: 11
  IrresponsibleModule: # Should be able to remove later!!!
    enabled: false
  FeatureEnvy:
    enabled: false
  ControlParameter:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  BooleanParameter:
    enabled: false
  DuplicateMethodCall:
    max_calls: 3
    allow_calls: [config, Utils::Print]
  InstanceVariableAssumption: # Should fix
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  LongParameterList:
    max_params: 4
  ManualDispatch:
    enabled: false