---
detectors:
  TooManyStatements:
      max_statements: 12
  IrresponsibleModule: # Should be able to remove later!!!
    enabled: false
  FeatureEnvy:
    enabled: false
  ControlParameter:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  BooleanParameter:
    enabled: false
  DuplicateMethodCall:
    max_calls: 2
    allow_calls: [config, Utils::Print]
  InstanceVariableAssumption: # Should fix
    enabled: false
  NestedIterators:
    ignore_iterators: [find, tap]