AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable
Style/StringLiterals:
  Enabled: true
Style/StringLiteralsInInterpolation:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Layout/LineLength:
  AllowedPatterns: [!ruby/regexp /\A#/, 'Parallel', 'config ', 'raise ', 'warn ', '_option ']
Metrics/MethodLength:
  Max: 13
Metrics/ModuleLength: 
  Max: 150
Metrics/AbcSize:
  Max: 25
Metrics/ParameterLists:
  Max: 5
Metrics/CyclomaticComplexity:
  Max: 10