AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable
Style/StringLiterals:
  Enabled: true
Style/StringLiteralsInInterpolation:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Layout/LineLength:
  AllowedPatterns:
    - !ruby/regexp /\A#/
    - 'raise '
    - 'warn '
Style/OpenStructUse:
  Enabled: false
Metrics/MethodLength:
  Max: 12
Metrics/AbcSize:
  Max: 22