AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable
Style/StringLiterals:
  Enabled: true
Style/StringLiteralsInInterpolation:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Layout/LineLength:
  AllowedPatterns:
    - !ruby/regexp /\A#/
    - 'config '
    - 'raise '
    - 'warn '
Metrics/MethodLength:
  Max: 13
Metrics/AbcSize:
  Max: 22
Metrics/ParameterLists:
  Max: 5