name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: test
        run: bundle exec rake
      - name: demo
        run: |
          bundle exec wax --version
          bundle exec wax --help
          bundle exec wax build collection --help
